version: "3.9"

services:
  fastapi:
    build: .
    container_name: sugarai-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app        
      - ./__secrets:/app/__secrets:ro
    env_file:
      - .env.local            # â† loads every key in .env
    restart: unless-stopped
